#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ssh_nivose="ssh pierrech@nivose.informatique.univ-paris-diderot.fr"
export XDG_CONFIG_HOME="$HOME"

export TERM="xterm-256color"

setopt RM_STAR_WAIT PRINT_EXIT_VALUE ALIASES

export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nvim'
fi

