#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# environement variables
export XDG_CONFIG_HOME="$HOME/.dotfiles"
export TERM="xterm-256color"
export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nvim'
fi

# shell options
setopt RM_STAR_WAIT PRINT_EXIT_VALUE ALIASES
setopt CDABLEVARS CORRECT HISTIGNOREDUPS NOCLOBBER

# aliases
alias ssh_nivose="ssh pierrech@nivose.informatique.univ-paris-diderot.fr"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
