#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# environement variables
export TERM="xterm-256color"
export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export PAGER='less'

if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nvim'
fi

# shell options
setopt RM_STAR_WAIT PRINT_EXIT_VALUE ALIASES
setopt CDABLEVARS CORRECT HISTIGNOREDUPS NOCLOBBER

# aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
